import type { Metadata } from 'next'
import { Crimson_Text } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Crimson_Text({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Luxe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <header>
        <Navbar />
       </header>
       <main> {children}</main>
       <footer>
        <Footer />
       </footer>
        </body>
    </html>
  )
}
