import type { Metadata } from 'next'
import { Crimson_Text } from 'next/font/google'
import '../styles/globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Provider from '@/provider/Provider'

const inter = Crimson_Text({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Luxe',
  description: 'Generated by create next app',
  verification:{
    google: "xzfiIgCMJtFBQ48siCvMDQRe5Wx2YIvPboKiNh0PYyc",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
      <header>
        <Header />
       </header>
       <main> {children}</main>
       <footer>
        <Footer />
       </footer>
      </Provider>
        </body>
    </html>
  )
}
