import type { Metadata } from 'next'
import "../../styles/globals.css"
import Provider from "@/provider/Provider"
import { Crimson_Text } from 'next/font/google'

const inter = Crimson_Text({
    subsets: ['latin'],
    weight: ['400', '600', '700'],
  })
  
  export const metadata: Metadata = {
    title: 'Luxe | Login ',
    description: 'Generated by create next app',
  }
  

export default function AuthLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>
                <main> {children}</main>
                </Provider>
            </body>
        </html>
    ) 
  }